#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSUI.BA.Rating.Data.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BAGLRatingDB")]
	public partial class RSUIDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public RSUIDataClassesDataContext() : 
				base(global::RSUI.BA.Rating.Data.Properties.Settings.Default.BAGLRatingDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RSUIDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RSUIDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RSUIDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RSUIDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GLTerritory> GLTerritories
		{
			get
			{
				return this.GetTable<GLTerritory>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GLTerritory")]
	public partial class GLTerritory
	{
		
		private string _State;
		
		private string _Zip;
		
		private string _City;
		
		private string _PreDirection;
		
		private string _StreetName;
		
		private string _PostDirection;
		
		private string _StreetType;
		
		private string _LowAddressNumber;
		
		private string _HighAddressNumber;
		
		private System.Nullable<char> _OEBFlag;
		
		private string _CountyFIPS;
		
		private string _GLTerritoryCode;
		
		public GLTerritory()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this._Zip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(30)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreDirection", DbType="VarChar(2)")]
		public string PreDirection
		{
			get
			{
				return this._PreDirection;
			}
			set
			{
				if ((this._PreDirection != value))
				{
					this._PreDirection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetName", DbType="VarChar(30)")]
		public string StreetName
		{
			get
			{
				return this._StreetName;
			}
			set
			{
				if ((this._StreetName != value))
				{
					this._StreetName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostDirection", DbType="VarChar(2)")]
		public string PostDirection
		{
			get
			{
				return this._PostDirection;
			}
			set
			{
				if ((this._PostDirection != value))
				{
					this._PostDirection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetType", DbType="VarChar(4)")]
		public string StreetType
		{
			get
			{
				return this._StreetType;
			}
			set
			{
				if ((this._StreetType != value))
				{
					this._StreetType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowAddressNumber", DbType="VarChar(11)")]
		public string LowAddressNumber
		{
			get
			{
				return this._LowAddressNumber;
			}
			set
			{
				if ((this._LowAddressNumber != value))
				{
					this._LowAddressNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighAddressNumber", DbType="VarChar(11)")]
		public string HighAddressNumber
		{
			get
			{
				return this._HighAddressNumber;
			}
			set
			{
				if ((this._HighAddressNumber != value))
				{
					this._HighAddressNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OEBFlag", DbType="Char(1)")]
		public System.Nullable<char> OEBFlag
		{
			get
			{
				return this._OEBFlag;
			}
			set
			{
				if ((this._OEBFlag != value))
				{
					this._OEBFlag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountyFIPS", DbType="Char(3)")]
		public string CountyFIPS
		{
			get
			{
				return this._CountyFIPS;
			}
			set
			{
				if ((this._CountyFIPS != value))
				{
					this._CountyFIPS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GLTerritoryCode", DbType="Char(3)")]
		public string GLTerritoryCode
		{
			get
			{
				return this._GLTerritoryCode;
			}
			set
			{
				if ((this._GLTerritoryCode != value))
				{
					this._GLTerritoryCode = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
